import type { Metadata } from "next";
import { Indie_Flower, Inter, Raleway } from "next/font/google";
import Link from "next/link";
import styles from "./layout.module.css";
import "./styles/globals.css";
import "./styles/theme.css";
import "./styles/tippy.css";
import "./styles/typography.css";

const inter = Inter({ subsets: ["latin"] });
const raleway = Raleway({ subsets: ["latin"] });
const indieFlower = Indie_Flower({ weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} ${inter.className} ${indieFlower.className}`}
      >
        <main className={styles.main}>
          <nav className={styles.nav}>
            <div>{" Salary Shuffle"}</div>
            <Link href="/">tldr</Link>
            <Link href="/fhss">FHSS</Link>
            <Link href="/expats">Expats</Link>
            <Link href="/carryForward">Carry Forwards</Link>
            <Link href="/voluntary">Voluntary Contributions</Link>
            <Link href="/hecs">HECS</Link>
            <Link href="/extraBenefits">Why super good</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
