import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <nav>
            {" Salary Shuffle"}
            <Link href="/">tldr</Link>
            <Link href="/fhss">FHSS</Link>
            <Link href="/expats">Expats</Link>
            <Link href="/voluntary">Voluntary Contributions</Link>
            <Link href="/hecs">HECS</Link>
            <Link href="/extraBenefits">Why super good</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
